[profile.default]
auto_detect_solc = false
solc_version = '0.8.11'
optimizer = true
optimizer_runs = 200
offline = true

# Directory Config
src = 'solidity/src'
test = 'solidity/test'
out = 'build/artifacts/forge'
libs = ['solidity/lib']
cache_path = 'build/cache/forge'
cache = true
force = false

# Test Config
ffi = false
sender = '0x000000000000000000000000000000000000000C'
tx_origin = '0x000000000000000000000000000000000000000C'
initial_balance = '0x000000000000000000000000'
block_number = 1
chain_id = 31337
gas_limit = 9223372036854775807
gas_price = 0
block_base_fee_per_gas = 0
block_timestamp = 1
block_difficulty = 0
gas_reports = ["*"]
no_storage_caching = false
revert_strings = "default"
bytecode_hash = "ipfs"
memory_limit = 33554432
verbosity = 1

[fuzz]
runs = 2048
max_test_rejects = 1000000

